<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.dvdforum.org/2005/HDDVDVideo/Playlist" targetNamespace="http://www.dvdforum.org/2005/HDDVDVideo/Playlist" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- (C)Copyright 2005 The DVD Forum*. All rights reserved. -->
	<!-- This schema were co-developed by Sonic Solutions and Toshiba -->
	<!-- Modifications contributed by Microsoft -->
	<!--Schema version: 16 Jul 2006-->
	<!--HD-DVD Specification version: 1.0-->
	<xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="http://www.w3.org/2001/xml.xsd"/>
	<xs:element name="Playlist">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #1</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Configuration"/>
				<xs:element ref="MediaAttributeList" minOccurs="0"/>
				<xs:element ref="TitleSet"/>
			</xs:sequence>
			<xs:attribute name="majorVersion" type="xs:nonNegativeInteger" use="required"/>
			<xs:attribute name="minorVersion" type="xs:nonNegativeInteger" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
			<xs:attribute name="displayName" type="xs:string" use="optional"/>
			<xs:attribute name="type" use="optional" default="Advanced">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="Advanced"/>
						<xs:enumeration value="Interoperable"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="TitleSet">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #2</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="FirstPlayTitle" minOccurs="0"/>
				<xs:element ref="Title" maxOccurs="999"/>
				<xs:element ref="PlaylistApplication" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="timeBase" type="FrameRateType" use="required"/>
			<xs:attribute name="tickBase" type="TickRateType" use="optional"/>
			<xs:attribute name="defaultLanguage" type="ISO639-2" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Title">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #3</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence minOccurs="0">
				<xs:choice maxOccurs="299">
					<xs:element ref="PrimaryAudioVideoClip"/>
					<xs:element ref="SecondaryAudioVideoClip"/>
					<xs:element ref="SubstituteAudioVideoClip"/>
					<xs:element ref="SubstituteAudioClip"/>
					<xs:element ref="AdvancedSubtitleSegment"/>
					<xs:element ref="ApplicationSegment"/>
				</xs:choice>
				<xs:element ref="TitleResource" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="ScheduledControlList" minOccurs="0"/>
				<xs:element ref="ChapterList" minOccurs="0"/>
				<xs:element ref="TrackNavigationList" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="titleNumber" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="type" use="optional" default="Advanced">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="Advanced"/>
						<xs:enumeration value="Original"/>
						<xs:enumeration value="UserDefined"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="selectable" type="xs:boolean" use="optional" default="true"/>
			<xs:attribute name="tickBaseDivisor" type="xs:positiveInteger" use="optional" default="1"/>
			<xs:attribute name="titleDuration" type="TimeExpressionType" use="required"/>
			<xs:attribute name="parentalLevel" type="ParentalListType" use="optional" default="*:1"/>
			<xs:attribute name="onEnd" type="xs:IDREF" use="optional"/>
			<xs:attribute name="displayName" type="xs:string" use="optional"/>
			<xs:attribute name="alternativeSDDisplayMode" type="SDDisplayModeType" use="optional" default="panscanOrLetterbox"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="FirstPlayTitle">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #4</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element ref="PrimaryAudioVideoClip"/>
				<xs:element ref="SubstituteAudioVideoClip"/>
			</xs:choice>
			<xs:attribute name="titleDuration" type="TimeExpressionType" use="required"/>
			<xs:attribute name="alternativeSDDisplayMode" type="SDDisplayModeType" use="optional" default="panscanOrLetterbox"/>
			<xs:attribute ref="xml:base" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="PrimaryAudioVideoClip">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #5</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ClipMappingType">
					<xs:sequence>
						<xs:element ref="Video" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="Audio" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="Subtitle" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="SubVideo" minOccurs="0"/>
						<xs:element ref="SubAudio" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="dataSource" type="DataSourceDiscOnlyType" use="optional" default="Disc"/>
					<xs:attribute name="seamless" type="xs:boolean" use="optional" default="false"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubstituteAudioVideoClip">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #6</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ClipMappingType">
					<xs:sequence>
						<xs:element ref="NetworkSource" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="Video" minOccurs="0"/>
						<xs:element ref="Audio" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="dataSource" type="DataSourceType" use="optional" default="P-Storage"/>
					<xs:attribute name="sync" type="SyncHNType" use="optional" default="hard"/>
					<xs:attribute name="preload" type="TimeExpressionType" use="optional"/>
					<xs:attribute name="noCache" type="xs:boolean" use="optional" default="false"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="SecondaryAudioVideoClip">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #7</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ClipMappingType">
					<xs:sequence>
						<xs:element ref="NetworkSource" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="SubVideo" minOccurs="0"/>
						<xs:element ref="SubAudio" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="dataSource" type="DataSourceType" use="optional" default="P-Storage"/>
					<xs:attribute name="sync" type="SyncHSNType" use="optional" default="soft"/>
					<xs:attribute name="preload" type="TimeExpressionType" use="optional"/>
					<xs:attribute name="noCache" type="xs:boolean" use="optional" default="false"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubstituteAudioClip">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #8</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ClipMappingType">
					<xs:sequence>
						<xs:element ref="NetworkSource" minOccurs="0" maxOccurs="unbounded"/>
						<xs:element ref="Audio" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="dataSource" type="DataSourceType" use="optional" default="P-Storage"/>
					<xs:attribute name="preload" type="TimeExpressionType" use="optional"/>
					<xs:attribute name="sync" type="SyncHSType" use="optional" default="soft"/>
					<xs:attribute name="noCache" type="xs:boolean" use="optional" default="false"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="AdvancedSubtitleSegment">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #9</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ObjectMappingType">
					<xs:sequence>
						<xs:element ref="Subtitle" maxOccurs="unbounded"/>
						<xs:element ref="ApplicationResource" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="sync" type="SyncHSType" use="optional" default="hard"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ApplicationSegment">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #10</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ObjectMappingType">
					<xs:sequence>
						<xs:element ref="ApplicationResource" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="sync" type="SyncHSType" use="optional" default="hard"/>
					<xs:attribute name="zOrder" type="xs:nonNegativeInteger" use="required"/>
					<xs:attribute name="language" type="ISO639-2" use="optional"/>
					<xs:attribute name="appBlock" type="xs:positiveInteger" use="optional"/>
					<xs:attribute name="group" type="xs:positiveInteger" use="optional"/>
					<xs:attribute name="autorun" type="xs:boolean" use="optional" default="true"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="PlaylistApplication">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #11</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="PlaylistApplicationResource" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="src" type="xs:anyURI" use="required"/>
			<xs:attribute name="language" type="ISO639-2" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ApplicationResource" type="ResourceType">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #12</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:element name="TitleResource">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #13</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="ResourceType">
					<xs:attribute name="titleTimeBegin" type="TimeExpressionType" use="required"/>
					<xs:attribute name="titleTimeEnd" type="TimeExpressionType" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="PlaylistApplicationResource">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #14</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="src" type="xs:anyURI" use="required"/>
			<xs:attribute name="size" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="multiplexed" type="MultiplexedDataType" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="NetworkSource">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #15</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="src" type="xs:anyURI" use="required"/>
			<xs:attribute name="networkThroughput" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Video">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #16</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="TrackNumberAssignmentType">
					<xs:attribute name="track" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="9"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="angleNumber" use="optional" default="1">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="9"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Audio">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #17</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="TrackNumberAssignmentType">
					<xs:attribute name="track" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="8"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="streamNumber" use="optional" default="1">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="8"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="Subtitle">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #18</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="TrackNumberAssignmentType">
					<xs:attribute name="track" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="32"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="streamNumber" use="optional" default="1">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="32"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubVideo">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #19</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="TrackNumberAssignmentType">
					<xs:attribute name="track" use="required" fixed="1">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger"/>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubAudio">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #20</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="TrackNumberAssignmentType">
					<xs:attribute name="track" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="8"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="streamNumber" use="optional" default="1">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="8"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="TrackNavigationList">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #21</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="VideoTrack" minOccurs="0" maxOccurs="9"/>
				<xs:element ref="AudioTrack" minOccurs="0" maxOccurs="8"/>
				<xs:element ref="SubtitleTrack" minOccurs="0" maxOccurs="32"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="VideoTrack">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #22</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="TrackNavigationType">
					<xs:attribute name="track" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="9"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="AudioTrack">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #23</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="TrackNavigationType">
					<xs:attribute name="track" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="8"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="langcode" type="LangCodeType" use="required"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubtitleTrack">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #24</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="TrackNavigationType">
					<xs:attribute name="track" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:positiveInteger">
								<xs:maxInclusive value="32"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
					<xs:attribute name="langcode" type="LangCodeType" use="required"/>
					<xs:attribute name="forced" type="xs:boolean" use="optional" default="false"/>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="ScheduledControlList">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #25</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice maxOccurs="unbounded">
				<xs:element ref="PauseAt"/>
				<xs:element ref="Event"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="PauseAt">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #26</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="titleTime" type="TimeExpressionType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Event">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #27</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="titleTime" type="TimeExpressionType" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ChapterList">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #28</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:choice>
				<xs:element ref="Chapter" maxOccurs="1999"/>
			</xs:choice>
		</xs:complexType>
	</xs:element>
	<xs:element name="Chapter">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #29</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="titleTimeBegin" type="TimeExpressionType" use="required"/>
			<xs:attribute name="description" type="xs:string" use="optional"/>
			<xs:attribute name="id" type="xs:ID" use="optional"/>
			<xs:attribute name="displayName" type="xs:string" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="MediaAttributeList">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #30</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="VideoAttributeItem" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="AudioAttributeItem" minOccurs="0" maxOccurs="unbounded"/>
				<xs:element ref="SubpictureAttributeItem" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="AudioAttributeItem">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #31</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="index" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="codec" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="LPCM"/>
						<xs:enumeration value="DD+"/>
						<xs:enumeration value="DTS-HD"/>
						<xs:enumeration value="MLP"/>
						<xs:enumeration value="MPEG"/>
						<xs:enumeration value="AC-3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="sampleRate" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="sampleDepth" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="channels" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="bitrate" type="xs:positiveInteger" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="VideoAttributeItem">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #32</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="index" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="codec" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="MPEG-2"/>
						<xs:enumeration value="VC-1"/>
						<xs:enumeration value="AVC"/>
						<xs:enumeration value="MPEG-1"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="sampleAspectRatio" use="optional">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="16:9"/>
						<xs:enumeration value="4:3"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="horizontalResolution" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="verticalResolution" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="encodedFrameRate" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="sourceFrameRate" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="bitrate" type="xs:positiveInteger" use="optional"/>
			<xs:attribute name="activeAreaX1" type="xs:nonNegativeInteger" use="optional"/>
			<xs:attribute name="activeAreaY1" type="xs:nonNegativeInteger" use="optional"/>
			<xs:attribute name="activeAreaX2" type="xs:nonNegativeInteger" use="optional"/>
			<xs:attribute name="activeAreaY2" type="xs:nonNegativeInteger" use="optional"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="SubpictureAttributeItem">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #33</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="index" type="xs:positiveInteger" use="required"/>
			<xs:attribute name="codec" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:enumeration value="2bitRLC"/>
						<xs:enumeration value="8bitRLC"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Configuration">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #34</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="StreamingBuffer"/>
				<xs:element ref="Aperture"/>
				<xs:element ref="MainVideoDefaultColor"/>
				<xs:element ref="NetworkTimeout" minOccurs="0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="StreamingBuffer">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #35</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="size" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:pattern value="([1-9][0-9]*)?[02468]"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="Aperture">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #36</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="size" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:NMTOKEN">
						<xs:enumeration value="1920x1080"/>
						<xs:enumeration value="1280x720"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="MainVideoDefaultColor">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #37</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="color" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:token">
						<xs:pattern value="[0-9A-F]{6}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="NetworkTimeout">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.14 #38</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="timeout" type="xs:nonNegativeInteger" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ResourceType">
		<xs:sequence>
			<xs:element ref="NetworkSource" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="src" type="xs:anyURI" use="required"/>
		<xs:attribute name="size" type="xs:positiveInteger" use="required"/>
		<xs:attribute name="priority" type="xs:nonNegativeInteger" use="required"/>
		<xs:attribute name="multiplexed" type="MultiplexedDataType" use="required"/>
		<xs:attribute name="loadingBegin" type="TimeExpressionType" use="optional"/>
		<xs:attribute name="noCache" type="xs:boolean" use="optional" default="false"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:complexType name="ObjectMappingType" mixed="false">
		<xs:attribute name="titleTimeBegin" type="TimeExpressionType" use="required"/>
		<xs:attribute name="titleTimeEnd" type="TimeExpressionType" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
		<xs:attribute name="id" type="xs:ID" use="optional"/>
		<xs:attribute name="src" type="xs:anyURI" use="required"/>
	</xs:complexType>
	<xs:complexType name="ClipMappingType" mixed="false">
		<xs:attribute name="titleTimeBegin" type="TimeExpressionType" use="required"/>
		<xs:attribute name="clipTimeBegin" type="TimeExpressionType" use="optional" default="00:00:00:00"/>
		<xs:attribute name="titleTimeEnd" type="TimeExpressionType" use="required"/>
		<xs:attribute name="src" type="xs:anyURI" use="required"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
		<xs:attribute name="id" type="xs:ID" use="optional"/>
	</xs:complexType>
	<xs:complexType name="TrackNumberAssignmentType">
		<xs:attribute name="description" type="xs:string" use="optional"/>
		<xs:attribute name="mediaAttr" type="xs:positiveInteger" use="optional" default="1"/>
	</xs:complexType>
	<xs:complexType name="TrackNavigationType">
		<xs:attribute name="selectable" type="xs:boolean" use="optional" default="true"/>
		<xs:attribute name="description" type="xs:string" use="optional"/>
	</xs:complexType>
	<xs:simpleType name="TimeExpressionType">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.13 #1</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value="(([0-1][0-9])|(2[0-3])):[0-5][0-9]:[0-5][0-9]:[0-5][0-9]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FrameRateType">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.13 #2</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="50fps"/>
			<xs:enumeration value="60fps"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="TickRateType">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.13 #3</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:enumeration value="24fps"/>
			<xs:enumeration value="50fps"/>
			<xs:enumeration value="60fps"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="LangCodeType">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.13 #4</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value="(([a-z][a-z])|\*):[0-9A-F][0-9A-F]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ParentalListType">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.13 #6</xs:documentation>
		</xs:annotation>
		<xs:list itemType="ParentalDataType"/>
	</xs:simpleType>
	<xs:simpleType name="ParentalDataType">
		<xs:annotation>
			<xs:documentation>Spec. 6.2.3.13 #6</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:token">
			<xs:pattern value="([A-Z][A-Z]|\*):[1-8]"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DataSourceType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Disc"/>
			<xs:enumeration value="P-Storage"/>
			<xs:enumeration value="Network"/>
			<xs:enumeration value="FileCache"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DataSourceDiscOnlyType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="Disc"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SyncHSNType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="hard"/>
			<xs:enumeration value="soft"/>
			<xs:enumeration value="none"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SyncHSType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="hard"/>
			<xs:enumeration value="soft"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SyncHNType">
		<xs:restriction base="xs:NMTOKEN">
			<xs:enumeration value="hard"/>
			<xs:enumeration value="none"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SDDisplayModeType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="panscanOrLetterbox"/>
			<xs:enumeration value="panscan"/>
			<xs:enumeration value="letterbox"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MultiplexedDataType">
		<xs:union>
			<xs:simpleType>
				<xs:restriction base="xs:token">
					<xs:enumeration value="false"/>
				</xs:restriction>
			</xs:simpleType>
			<xs:simpleType>
				<xs:restriction base="xs:nonNegativeInteger"/>
			</xs:simpleType>
		</xs:union>
	</xs:simpleType>
	<xs:simpleType name="ISO639-2">
		<xs:restriction base="xs:token">
			<xs:enumeration value="ab"/>
			<xs:enumeration value="aa"/>
			<xs:enumeration value="af"/>
			<xs:enumeration value="ak"/>
			<xs:enumeration value="sq"/>
			<xs:enumeration value="am"/>
			<xs:enumeration value="ar"/>
			<xs:enumeration value="an"/>
			<xs:enumeration value="hy"/>
			<xs:enumeration value="as"/>
			<xs:enumeration value="av"/>
			<xs:enumeration value="ae"/>
			<xs:enumeration value="ay"/>
			<xs:enumeration value="az"/>
			<xs:enumeration value="bm"/>
			<xs:enumeration value="ba"/>
			<xs:enumeration value="eu"/>
			<xs:enumeration value="be"/>
			<xs:enumeration value="bn"/>
			<xs:enumeration value="bh"/>
			<xs:enumeration value="bi"/>
			<xs:enumeration value="nb"/>
			<xs:enumeration value="bs"/>
			<xs:enumeration value="br"/>
			<xs:enumeration value="bg"/>
			<xs:enumeration value="my"/>
			<xs:enumeration value="es"/>
			<xs:enumeration value="ca"/>
			<xs:enumeration value="ch"/>
			<xs:enumeration value="ce"/>
			<xs:enumeration value="ny"/>
			<xs:enumeration value="ny"/>
			<xs:enumeration value="zh"/>
			<xs:enumeration value="za"/>
			<xs:enumeration value="cu"/>
			<xs:enumeration value="cu"/>
			<xs:enumeration value="cv"/>
			<xs:enumeration value="kw"/>
			<xs:enumeration value="co"/>
			<xs:enumeration value="cr"/>
			<xs:enumeration value="hr"/>
			<xs:enumeration value="cs"/>
			<xs:enumeration value="da"/>
			<xs:enumeration value="dv"/>
			<xs:enumeration value="nl"/>
			<xs:enumeration value="dz"/>
			<xs:enumeration value="en"/>
			<xs:enumeration value="eo"/>
			<xs:enumeration value="et"/>
			<xs:enumeration value="ee"/>
			<xs:enumeration value="fo"/>
			<xs:enumeration value="fj"/>
			<xs:enumeration value="fi"/>
			<xs:enumeration value="nl"/>
			<xs:enumeration value="fr"/>
			<xs:enumeration value="ff"/>
			<xs:enumeration value="gd"/>
			<xs:enumeration value="gl"/>
			<xs:enumeration value="lg"/>
			<xs:enumeration value="ka"/>
			<xs:enumeration value="de"/>
			<xs:enumeration value="ki"/>
			<xs:enumeration value="el"/>
			<xs:enumeration value="kl"/>
			<xs:enumeration value="gn"/>
			<xs:enumeration value="gu"/>
			<xs:enumeration value="ht"/>
			<xs:enumeration value="ht"/>
			<xs:enumeration value="ha"/>
			<xs:enumeration value="he"/>
			<xs:enumeration value="hz"/>
			<xs:enumeration value="hi"/>
			<xs:enumeration value="ho"/>
			<xs:enumeration value="hu"/>
			<xs:enumeration value="is"/>
			<xs:enumeration value="io"/>
			<xs:enumeration value="ig"/>
			<xs:enumeration value="id"/>
			<xs:enumeration value="ia"/>
			<xs:enumeration value="ie"/>
			<xs:enumeration value="iu"/>
			<xs:enumeration value="ik"/>
			<xs:enumeration value="ga"/>
			<xs:enumeration value="it"/>
			<xs:enumeration value="ja"/>
			<xs:enumeration value="jv"/>
			<xs:enumeration value="kl"/>
			<xs:enumeration value="kn"/>
			<xs:enumeration value="kr"/>
			<xs:enumeration value="ks"/>
			<xs:enumeration value="kk"/>
			<xs:enumeration value="km"/>
			<xs:enumeration value="ki"/>
			<xs:enumeration value="rw"/>
			<xs:enumeration value="ky"/>
			<xs:enumeration value="kv"/>
			<xs:enumeration value="kg"/>
			<xs:enumeration value="ko"/>
			<xs:enumeration value="kj"/>
			<xs:enumeration value="ku"/>
			<xs:enumeration value="kj"/>
			<xs:enumeration value="lo"/>
			<xs:enumeration value="la"/>
			<xs:enumeration value="lv"/>
			<xs:enumeration value="lb"/>
			<xs:enumeration value="li"/>
			<xs:enumeration value="li"/>
			<xs:enumeration value="li"/>
			<xs:enumeration value="ln"/>
			<xs:enumeration value="lt"/>
			<xs:enumeration value="lu"/>
			<xs:enumeration value="lb"/>
			<xs:enumeration value="mk"/>
			<xs:enumeration value="mg"/>
			<xs:enumeration value="ms"/>
			<xs:enumeration value="ml"/>
			<xs:enumeration value="mt"/>
			<xs:enumeration value="gv"/>
			<xs:enumeration value="mi"/>
			<xs:enumeration value="mr"/>
			<xs:enumeration value="mh"/>
			<xs:enumeration value="mo"/>
			<xs:enumeration value="mn"/>
			<xs:enumeration value="na"/>
			<xs:enumeration value="nv"/>
			<xs:enumeration value="nv"/>
			<xs:enumeration value="nd"/>
			<xs:enumeration value="nr"/>
			<xs:enumeration value="ng"/>
			<xs:enumeration value="ne"/>
			<xs:enumeration value="se"/>
			<xs:enumeration value="nd"/>
			<xs:enumeration value="no"/>
			<xs:enumeration value="nb"/>
			<xs:enumeration value="nn"/>
			<xs:enumeration value="ny"/>
			<xs:enumeration value="nn"/>
			<xs:enumeration value="oc"/>
			<xs:enumeration value="oj"/>
			<xs:enumeration value="cu"/>
			<xs:enumeration value="cu"/>
			<xs:enumeration value="cu"/>
			<xs:enumeration value="or"/>
			<xs:enumeration value="om"/>
			<xs:enumeration value="os"/>
			<xs:enumeration value="os"/>
			<xs:enumeration value="pi"/>
			<xs:enumeration value="pa"/>
			<xs:enumeration value="fa"/>
			<xs:enumeration value="pl"/>
			<xs:enumeration value="pt"/>
			<xs:enumeration value="oc"/>
			<xs:enumeration value="pa"/>
			<xs:enumeration value="ps"/>
			<xs:enumeration value="qu"/>
			<xs:enumeration value="rm"/>
			<xs:enumeration value="ro"/>
			<xs:enumeration value="rn"/>
			<xs:enumeration value="ru"/>
			<xs:enumeration value="sm"/>
			<xs:enumeration value="sg"/>
			<xs:enumeration value="sa"/>
			<xs:enumeration value="sc"/>
			<xs:enumeration value="gd"/>
			<xs:enumeration value="sr"/>
			<xs:enumeration value="sn"/>
			<xs:enumeration value="ii"/>
			<xs:enumeration value="sd"/>
			<xs:enumeration value="si"/>
			<xs:enumeration value="si"/>
			<xs:enumeration value="sk"/>
			<xs:enumeration value="sl"/>
			<xs:enumeration value="so"/>
			<xs:enumeration value="st"/>
			<xs:enumeration value="nr"/>
			<xs:enumeration value="es"/>
			<xs:enumeration value="su"/>
			<xs:enumeration value="sw"/>
			<xs:enumeration value="ss"/>
			<xs:enumeration value="sv"/>
			<xs:enumeration value="tl"/>
			<xs:enumeration value="ty"/>
			<xs:enumeration value="tg"/>
			<xs:enumeration value="ta"/>
			<xs:enumeration value="tt"/>
			<xs:enumeration value="te"/>
			<xs:enumeration value="th"/>
			<xs:enumeration value="bo"/>
			<xs:enumeration value="ti"/>
			<xs:enumeration value="to"/>
			<xs:enumeration value="ts"/>
			<xs:enumeration value="tn"/>
			<xs:enumeration value="tr"/>
			<xs:enumeration value="tk"/>
			<xs:enumeration value="tw"/>
			<xs:enumeration value="ug"/>
			<xs:enumeration value="uk"/>
			<xs:enumeration value="ur"/>
			<xs:enumeration value="ug"/>
			<xs:enumeration value="uz"/>
			<xs:enumeration value="ca"/>
			<xs:enumeration value="ve"/>
			<xs:enumeration value="vi"/>
			<xs:enumeration value="vo"/>
			<xs:enumeration value="wa"/>
			<xs:enumeration value="cy"/>
			<xs:enumeration value="fy"/>
			<xs:enumeration value="wo"/>
			<xs:enumeration value="xh"/>
			<xs:enumeration value="yi"/>
			<xs:enumeration value="yo"/>
			<xs:enumeration value="za"/>
			<xs:enumeration value="zu"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
